# Generated by Django 3.2.8 on 2021-10-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_admin', '0002_adding_help_docs'),
    ]

    def insertData(apps, schema_editor):
        Settings = apps.get_model('booking_admin', 'Settings')
        Settings(key="buffer_info", label="Buffer Information", value="", type="textarea").save()

    operations = [
        migrations.RunPython(insertData)
    ]
