# Generated by Django 3.2.6 on 2021-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def insertData(apps, schema_editor):
        Settings = apps.get_model('admin_settings', 'Settings')
        phone = Settings(key="phone", label="Phone", value="04 1234 5678", type="text")
        start_date = Settings(key="start_date", label="Global Start Date", value="00:00", type="time")
        end_date = Settings(key="end_date", label="Global End Date", value="00:00", type="time")

        phone.save()
        start_date.save()
        end_date.save()

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin_settings',
            },
        ),
        migrations.RunPython(insertData)
    ]
