# Generated by Django 3.2.6 on 2021-08-31 09:08

import app.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.authentication.models.CustomUserManager()),
            ],
        ),
    ]
