# Generated by Django 3.2.6 on 2021-09-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('carpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.carpark')),
            ],
        ),
    ]
