# Generated by Django 3.2.7 on 2021-09-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_carbay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbay',
            name='carpark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbays', to='parking.carpark'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('rego', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('carpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_carpark', to='parking.carpark')),
            ],
        ),
        migrations.CreateModel(
            name='BaysBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_bay', to='parking.carbay')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays_booked', to='parking.bookings')),
            ],
        ),
    ]
