# Generated by Django 3.2.7 on 2021-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbay',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
