# Generated by Django 3.2.7 on 2021-10-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
