# Generated by Django 3.2.7 on 2021-10-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_bookings_phone'),
        ('parking', '0006_alter_carbay_description'),
    ]

    operations = [
    ]
