# Generated by Django 3.2.6 on 2021-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def insertData(apps, schema_editor):
        Settings = apps.get_model('app_settings', 'Settings')
        phone = Settings(key="phone", value="04 1234 5678")
        phone.save()

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.RunPython(insertData)
    ]
